import {useEffect,useState} from "react";
import {useAuth} from "../../context/AuthContext";
import {supabase} from "../../lib/supabase";
import {navigate} from "../../lib/router";

type Vehicle={id:string;plate:string|null;renavam:string|null;brand:string|null;model:string|null;year_model:number|null};

export function VehiclesPage(){
 const{user}=useAuth();const[vehicles,setVehicles]=useState<Vehicle[]>([]);const[clients,setClients]=useState<{id:string;name:string}[]>([]);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[form,setForm]=useState({plate:"",renavam:"",brand:"",model:"",year_model:"",client_id:""});
 async function tenantId(){if(!supabase||!user)return null;const{data}=await supabase.from("memberships").select("tenant_id").eq("user_id",user.id).eq("active",true).limit(1).maybeSingle();return data?.tenant_id||null}
 async function load(){const tenant=await tenantId();if(!tenant||!supabase)return;const[v,c]=await Promise.all([supabase.from("vehicles").select("id,plate,renavam,brand,model,year_model").eq("tenant_id",tenant).order("created_at",{ascending:false}),supabase.from("clients").select("id,name").eq("tenant_id",tenant).order("name")]);if(v.error)setError(v.error.message);else setVehicles((v.data||[]) as Vehicle[]);if(!c.error)setClients((c.data||[]) as {id:string;name:string}[])}
 useEffect(()=>{void load()},[user]);
 async function save(e:React.FormEvent){e.preventDefault();setError("");if(!form.plate.trim()&&!form.renavam.trim()){setError("Informe a placa ou o RENAVAM.");return}setSaving(true);const tenant=await tenantId();if(!tenant||!supabase){setError("Sessão do escritório não encontrada.");setSaving(false);return}const{error}=await supabase.from("vehicles").insert({tenant_id:tenant,plate:form.plate.toUpperCase()||null,renavam:form.renavam||null,brand:form.brand||null,model:form.model||null,year_model:form.year_model?Number(form.year_model):null,client_id:form.client_id||null});setSaving(false);if(error){setError(error.message);return}setForm({plate:"",renavam:"",brand:"",model:"",year_model:"",client_id:""});setOpen(false);void load()}
 return <div className="page-stack"><section className="page-intro"><div><span className="eyebrow">CARTEIRA DE VEÍCULOS</span><h1>Veículos</h1><p>Centralize placa, RENAVAM, proprietário, situação e histórico de consultas.</p></div><button className="primary-button" onClick={()=>setOpen(!open)}>+ Cadastrar veículo</button></section>{open&&<form className="panel data-form" onSubmit={save}><div className="form-grid"><label>Placa<input value={form.plate} onChange={e=>setForm({...form,plate:e.target.value.toUpperCase()})} placeholder="ABC1D23"/></label><label>RENAVAM<input value={form.renavam} onChange={e=>setForm({...form,renavam:e.target.value})} placeholder="RENAVAM"/></label><label>Marca<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} placeholder="Ex.: Volkswagen"/></label><label>Modelo<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})} placeholder="Ex.: Gol"/></label><label>Ano modelo<input type="number" value={form.year_model} onChange={e=>setForm({...form,year_model:e.target.value})} placeholder="2026"/></label><label>Cliente<select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Sem vínculo</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?"Salvando...":"Salvar veículo"}</button></div></form>}<div className="search-card"><div><span className="eyebrow">CONSULTA RÁPIDA</span><h3>Consultar por placa</h3><p>O registro da consulta já pode ser preparado no histórico; a busca externa depende de fonte oficial ou autorizada.</p></div><button className="secondary-button" onClick={()=>navigate("consultas")}>Abrir central de consultas</button></div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">CARTEIRA</span><h3>Veículos cadastrados</h3></div><span className="muted">{vehicles.length} registro(s)</span></div>{vehicles.length===0?<div className="empty-inline">Nenhum veículo cadastrado ainda.</div>:<div className="data-list">{vehicles.map(v=><div className="data-row" key={v.id}><div><strong>{v.plate||"Sem placa"} — {v.brand||""} {v.model||""}</strong><small>RENAVAM: {v.renavam||"não informado"} • Ano: {v.year_model||"não informado"}</small></div></div>)}</div>}</div></div>
}