import {useEffect,useState} from "react";
import type {FormEvent} from "react";
import {useAuth} from "../../context/AuthContext";
import {supabase} from "../../lib/supabase";

type Appointment={id:string;title:string;starts_at:string;ends_at:string;status:string;location:string|null;notes:string|null;client_id:string|null};
type Client={id:string;name:string};
type Process={id:string;service_type:string;protocol:string|null};

export function AgendaPage(){
 const{user}=useAuth();const[items,setItems]=useState<Appointment[]>([]);const[clients,setClients]=useState<Client[]>([]);const[processes,setProcesses]=useState<Process[]>([]);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 const[form,setForm]=useState({title:"",client_id:"",process_id:"",date:"",start:"09:00",end:"10:00",location:"",notes:""});
 async function tenantId(){if(!supabase||!user)return null;const{data}=await supabase.from("memberships").select("tenant_id").eq("user_id",user.id).eq("active",true).limit(1).maybeSingle();return data?.tenant_id||null}
 async function load(){const tenant=await tenantId();if(!tenant||!supabase)return;const[a,c,p]=await Promise.all([supabase.from("appointments").select("id,title,starts_at,ends_at,status,location,notes,client_id").eq("tenant_id",tenant).order("starts_at",{ascending:true}),supabase.from("clients").select("id,name").eq("tenant_id",tenant).order("name"),supabase.from("transfer_processes").select("id,service_type,protocol").eq("tenant_id",tenant).order("opened_at",{ascending:false})]);if(a.error)setError(a.error.message);else setItems((a.data||[]) as Appointment[]);if(!c.error)setClients((c.data||[]) as Client[]);if(!p.error)setProcesses((p.data||[]) as Process[])}
 useEffect(()=>{void load()},[user]);
 async function save(e:FormEvent){e.preventDefault();setError("");if(!form.title.trim()||!form.date){setError("Informe o título e a data do compromisso.");return}if(form.end<=form.start){setError("O horário final precisa ser depois do inicial.");return}setSaving(true);const tenant=await tenantId();if(!tenant||!supabase){setError("Sessão do escritório não encontrada.");setSaving(false);return}const{error}=await supabase.from("appointments").insert({tenant_id:tenant,client_id:form.client_id||null,process_id:form.process_id||null,title:form.title.trim(),starts_at:new Date(form.date+"T"+form.start).toISOString(),ends_at:new Date(form.date+"T"+form.end).toISOString(),location:form.location||null,notes:form.notes||null,created_by:user?.id||null});setSaving(false);if(error){setError(error.message);return}setForm({title:"",client_id:"",process_id:"",date:"",start:"09:00",end:"10:00",location:"",notes:""});setOpen(false);void load()}
 function clientName(id:string|null){return clients.find(c=>c.id===id)?.name||"Sem cliente"}
 function processLabel(id:string|null){const p=processes.find(x=>x.id===id);return p?p.service_type+(p.protocol?" • "+p.protocol:""):"Sem processo"}
 function dateLabel(v:string){return new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}
 return <div className="page-stack"><section className="page-intro"><div><span className="eyebrow">ATENDIMENTOS</span><h1>Agenda</h1><p>Organize visitas, vistorias, entregas e compromissos do escritório.</p></div><button className="primary-button" onClick={()=>setOpen(!open)}>+ Novo compromisso</button></section>{open&&<form className="panel data-form" onSubmit={save}><div className="form-grid"><label>Título<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: Atendimento para transferência"/></label><label>Cliente<select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Sem cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Processo<select value={form.process_id} onChange={e=>setForm({...form,process_id:e.target.value})}><option value="">Sem processo</option>{processes.map(p=><option key={p.id} value={p.id}>{processLabel(p.id)}</option>)}</select></label><label>Data<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Início<input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Fim<input type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label><label>Local<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Endereço ou local"/></label></div><label className="full-field">Observações<textarea className="settings-textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Detalhes do atendimento"/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?"Salvando...":"Agendar"}</button></div></form>}{!open&&error&&<p className="form-error">{error}</p>}<div className="panel"><div className="panel-heading"><div><span className="eyebrow">COMPROMISSOS</span><h3>Próximos atendimentos</h3></div><span className="muted">{items.length} registro(s)</span></div>{items.length===0?<div className="empty-inline">Nenhum compromisso agendado.</div>:<div className="data-list">{items.map(i=><div className="data-row" key={i.id}><div><strong>{i.title}</strong><small>{dateLabel(i.starts_at)} → {new Date(i.ends_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})} • {clientName(i.client_id)}</small></div><span>{i.location||i.status}</span></div>)}</div>}</div></div>
}