import {useEffect,useState} from "react";
import type {FormEvent} from "react";
import {useAuth} from "../../context/AuthContext";
import {supabase} from "../../lib/supabase";

type Doc={id:string;process_id:string;name:string;document_type:string|null;required:boolean;status:string;notes:string|null};
type Process={id:string;service_type:string;protocol:string|null};
const labels=[["rg_cpf","RG / CPF"],["crlv","CRLV"],["atpv","ATPV-e"],["comprovante_endereco","Comprovante de endereço"],["procuracao","Procuração"],["outro","Outro"]];

export function DocumentsPage(){
 const{user}=useAuth();const[docs,setDocs]=useState<Doc[]>([]);const[processes,setProcesses]=useState<Process[]>([]);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 const[form,setForm]=useState({process_id:"",name:"",document_type:"outro",required:true,notes:""});
 async function tenantId(){if(!supabase||!user)return null;const{data}=await supabase.from("memberships").select("tenant_id").eq("user_id",user.id).eq("active",true).limit(1).maybeSingle();return data?.tenant_id||null}
 async function load(){const tenant=await tenantId();if(!tenant||!supabase)return;const[d,p]=await Promise.all([supabase.from("process_documents").select("id,process_id,name,document_type,required,status,notes").eq("tenant_id",tenant).order("created_at",{ascending:false}),supabase.from("transfer_processes").select("id,service_type,protocol").eq("tenant_id",tenant).order("opened_at",{ascending:false})]);if(d.error)setError(d.error.message);else setDocs((d.data||[]) as Doc[]);if(!p.error)setProcesses((p.data||[]) as Process[])}
 useEffect(()=>{void load()},[user]);
 async function save(e:FormEvent){e.preventDefault();setError("");if(!form.process_id||!form.name.trim()){setError("Selecione o processo e informe o documento.");return}setSaving(true);const tenant=await tenantId();if(!tenant||!supabase){setError("Sessão do escritório não encontrada.");setSaving(false);return}const{error}=await supabase.from("process_documents").insert({tenant_id:tenant,process_id:form.process_id,name:form.name.trim(),document_type:form.document_type,required:form.required,status:"pending",notes:form.notes||null});setSaving(false);if(error){setError(error.message);return}setForm({process_id:"",name:"",document_type:"outro",required:true,notes:""});setOpen(false);void load()}
 function processLabel(id:string){const p=processes.find(x=>x.id===id);return p?p.service_type+(p.protocol?" • "+p.protocol:""):"Processo"}
 return <div className="page-stack"><section className="page-intro"><div><span className="eyebrow">ARQUIVOS</span><h1>Documentos</h1><p>Controle os documentos exigidos por processo e acompanhe o que ainda está pendente.</p></div><button className="primary-button" onClick={()=>setOpen(!open)}>+ Adicionar documento</button></section>{open&&<form className="panel data-form" onSubmit={save}><div className="form-grid"><label>Processo<select value={form.process_id} onChange={e=>setForm({...form,process_id:e.target.value})}><option value="">Selecionar processo</option>{processes.map(p=><option key={p.id} value={p.id}>{processLabel(p.id)}</option>)}</select></label><label>Tipo<select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}>{labels.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Nome do documento<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Documento do proprietário"/></label><label className="checkbox-field"><input type="checkbox" checked={form.required} onChange={e=>setForm({...form,required:e.target.checked})}/> Documento obrigatório</label></div><label className="full-field">Observações<textarea className="settings-textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?"Salvando...":"Adicionar documento"}</button></div></form>}{!open&&error&&<p className="form-error">{error}</p>}<div className="panel"><div className="panel-heading"><div><span className="eyebrow">PENDÊNCIAS</span><h3>Documentos dos processos</h3></div><span className="muted">{docs.length} registro(s)</span></div>{docs.length===0?<div className="empty-inline">Nenhum documento cadastrado.</div>:<div className="data-list">{docs.map(d=><div className="data-row" key={d.id}><div><strong>{d.name}</strong><small>{processLabel(d.process_id)} • {d.required?"Obrigatório":"Opcional"}</small></div><span>{d.status==="pending"?"Pendente":"Concluído"}</span></div>)}</div>}</div></div>
}