import {useEffect,useState} from "react";
import {StatCard} from "../common/StatCard";
import {useAuth} from "../../context/AuthContext";
import {supabase} from "../../lib/supabase";
import {navigate} from "../../lib/router";

const defaults={dashboard_title:"Seu escritório organizado em um só lugar.",dashboard_description:"Tenha uma visão clara da operação e concentre clientes, veículos, processos, documentos, consultas e atendimentos em um único ambiente.",hero_status:"CENTRAL DE OPERAÇÃO",hero_card_title:"Estrutura pronta para a operação",hero_card_description:"Os módulos estão organizados para receber os dados reais do escritório com segurança e isolamento por empresa."};

export function DashboardPage(){
 const{user}=useAuth();const[copy,setCopy]=useState(defaults);
 useEffect(()=>{async function load(){if(!supabase||!user)return;const{data:m}=await supabase.from("memberships").select("tenant_id").eq("user_id",user.id).eq("active",true).limit(1).maybeSingle();if(!m?.tenant_id)return;const{data}=await supabase.from("site_settings").select("settings").eq("tenant_id",m.tenant_id).maybeSingle();if(data?.settings)setCopy({...defaults,...data.settings});}void load();},[user]);
 return <div className="page-stack"><section className="hero-panel"><div><span className="status-pill">{copy.hero_status}</span><h1>{copy.dashboard_title}</h1><p>{copy.dashboard_description}</p></div><div className="hero-card"><span>Visão do sistema</span><strong>{copy.hero_card_title}</strong><small>{copy.hero_card_description}</small></div></section><section className="stats-grid"><StatCard label="Clientes" value="0" detail="Cadastros ativos" icon="◉"/><StatCard label="Veículos" value="0" detail="Veículos cadastrados" icon="▣"/><StatCard label="Processos" value="0" detail="Em andamento" icon="↗"/><StatCard label="Agenda" value="0" detail="Compromissos de hoje" icon="◷"/></section><section className="dashboard-grid"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">ACOMPANHAMENTO</span><h3>Processos recentes</h3></div><span className="muted">Atualizações do escritório</span></div><div className="timeline-empty"><div className="timeline-line"/><p>Quando houver processos cadastrados, as movimentações mais recentes aparecerão aqui para facilitar o acompanhamento.</p></div></article><article className="panel"><div className="panel-heading"><div><span className="eyebrow">ACESSO RÁPIDO</span><h3>Principais ações</h3></div></div><div className="shortcut-grid">{[["Cadastrar cliente","clientes"],["Cadastrar veículo","veiculos"],["Abrir processo","processos"],["Consultar placa","veiculos"],["Consultar IPVA","ipva"],["Agendar atendimento","agenda"]].map(([label,route])=><button className="shortcut-card" key={label} onClick={()=>navigate(route as "clientes"|"veiculos"|"processos"|"ipva"|"agenda")}>{label}<span>→</span></button>)}</div></article></section></div>}
