import {useEffect,useState} from "react";
import {useAuth} from "../../context/AuthContext";
import {supabase} from "../../lib/supabase";

type Client={id:string;name:string;document:string|null;phone:string|null;email:string|null;city:string|null};

export function ClientsPage(){
 const{user}=useAuth();const[clients,setClients]=useState<Client[]>([]);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[form,setForm]=useState({name:"",document:"",phone:"",email:"",city:""});
 async function tenantId(){if(!supabase||!user)return null;const{data}=await supabase.from("memberships").select("tenant_id").eq("user_id",user.id).eq("active",true).limit(1).maybeSingle();return data?.tenant_id||null}
 async function load(){const tenant=await tenantId();if(!tenant||!supabase)return;const{data,error}=await supabase.from("clients").select("id,name,document,phone,email,city").eq("tenant_id",tenant).order("created_at",{ascending:false});if(error)setError(error.message);else setClients((data||[]) as Client[])}
 useEffect(()=>{void load()},[user]);
 async function save(e:React.FormEvent){e.preventDefault();setError("");if(!form.name.trim()){setError("Informe o nome do cliente.");return}setSaving(true);const tenant=await tenantId();if(!tenant||!supabase){setError("Sessão do escritório não encontrada.");setSaving(false);return}const{error}=await supabase.from("clients").insert({tenant_id:tenant,name:form.name.trim(),document:form.document||null,phone:form.phone||null,email:form.email||null,city:form.city||null});setSaving(false);if(error){setError(error.message);return}setForm({name:"",document:"",phone:"",email:"",city:""});setOpen(false);void load()}
 return <div className="page-stack"><section className="page-intro"><div><span className="eyebrow">CADASTRO DE CLIENTES</span><h1>Clientes</h1><p>Centralize os dados dos clientes e o histórico de atendimento do escritório.</p></div><button className="primary-button" onClick={()=>setOpen(!open)}>+ Novo cliente</button></section>{open&&<form className="panel data-form" onSubmit={save}><div className="form-grid"><label>Nome completo<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome do cliente"/></label><label>CPF/CNPJ<input value={form.document} onChange={e=>setForm({...form,document:e.target.value})} placeholder="CPF ou CNPJ"/></label><label>Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="(31) 99999-9999"/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="cliente@email.com"/></label><label>Cidade<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Cidade"/></label></div>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?"Salvando...":"Salvar cliente"}</button></div></form>}{!open&&error&&<p className="form-error">{error}</p>}<div className="panel"><div className="panel-heading"><div><span className="eyebrow">REGISTROS</span><h3>Clientes cadastrados</h3></div><span className="muted">{clients.length} registro(s)</span></div>{clients.length===0?<div className="empty-inline">Nenhum cliente cadastrado ainda.</div>:<div className="data-list">{clients.map(c=><div className="data-row" key={c.id}><div><strong>{c.name}</strong><small>{c.document||"Sem documento"} • {c.phone||"Sem telefone"}</small></div><span>{c.city||c.email||""}</span></div>)}</div>}</div></div>
}