import {useEffect,useMemo,useState} from "react";
import type {FormEvent} from "react";
import {useAuth} from "../../context/AuthContext";
import {supabase} from "../../lib/supabase";

type Client={id:string;name:string;document:string|null;rg:string|null;email:string|null;phone:string|null;whatsapp:string|null;address:string|null;city:string|null;state:string|null;notes:string|null};
type Form={name:string;document:string;rg:string;email:string;phone:string;whatsapp:string;address:string;city:string;state:string;notes:string};
const emptyForm:Form={name:"",document:"",rg:"",email:"",phone:"",whatsapp:"",address:"",city:"",state:"MG",notes:""};

export function ClientsPage(){
 const{user}=useAuth();const[clients,setClients]=useState<Client[]>([]);const[clientVehicles,setClientVehicles]=useState<Record<string,{id:string;plate:string|null;renavam:string|null;brand:string|null;model:string|null;year_model:number|null}[]>>({});const[selectedClient,setSelectedClient]=useState<string|null>(null);const[vehicleOpen,setVehicleOpen]=useState(false);const[vehicleForm,setVehicleForm]=useState({plate:"",renavam:"",brand:"",model:"",year_model:""});const[open,setOpen]=useState(false);const[editing,setEditing]=useState<string|null>(null);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[search,setSearch]=useState("");const[form,setForm]=useState<Form>(emptyForm);
 async function tenantId(){if(!supabase||!user)return null;const{data}=await supabase.from("memberships").select("tenant_id").eq("user_id",user.id).eq("active",true).limit(1).maybeSingle();return data?.tenant_id||null}

 async function loadVehicles(tenant:string,clientList:Client[]){if(!supabase)return;const{data}=await supabase.from("vehicles").select("id,plate,renavam,brand,model,year_model,client_id").eq("tenant_id",tenant).not("client_id","is",null);const grouped:Record<string,{id:string;plate:string|null;renavam:string|null;brand:string|null;model:string|null;year_model:number|null}[]>= {};for(const v of (data||[])){if(!v.client_id)continue;(grouped[v.client_id]??=[]).push(v as never)}for(const cl of clientList)grouped[cl.id]=grouped[cl.id]||[];setClientVehicles(grouped)}
 async function load(){const tenant=await tenantId();if(!tenant||!supabase)return;const{data,error}=await supabase.from("clients").select("id,name,document,rg,email,phone,whatsapp,address,city,state,notes").eq("tenant_id",tenant).order("created_at",{ascending:false});if(error)setError(error.message);else{const list=(data||[]) as Client[];setClients(list);void loadVehicles(tenant,list)}}
 useEffect(()=>{void load()},[user]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return clients;return clients.filter(c=>[c.name,c.document,c.phone,c.whatsapp,c.email,c.city].some(v=>v?.toLowerCase().includes(q)))},[clients,search]);
 function startNew(){setEditing(null);setForm(emptyForm);setError("");setOpen(true)}
 function startEdit(c:Client){setEditing(c.id);setForm({name:c.name,document:c.document||"",rg:c.rg||"",email:c.email||"",phone:c.phone||"",whatsapp:c.whatsapp||"",address:c.address||"",city:c.city||"",state:c.state||"MG",notes:c.notes||""});setError("");setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();setError("");if(!form.name.trim()){setError("Informe o nome do cliente.");return}setSaving(true);const tenant=await tenantId();if(!tenant||!supabase){setError("Sessão do escritório não encontrada.");setSaving(false);return}const payload={name:form.name.trim(),document:form.document||null,rg:form.rg||null,email:form.email||null,phone:form.phone||null,whatsapp:form.whatsapp||null,address:form.address||null,city:form.city||null,state:form.state.toUpperCase()||"MG",notes:form.notes||null};const result=editing?await supabase.from("clients").update(payload).eq("id",editing).eq("tenant_id",tenant):await supabase.from("clients").insert({tenant_id:tenant,...payload});setSaving(false);if(result.error){setError(result.error.message);return}setForm(emptyForm);setEditing(null);setOpen(false);void load()}
 return <div className="page-stack"><section className="page-intro"><div><span className="eyebrow">CADASTRO DE CLIENTES</span><h1>Clientes</h1><p>Cadastre, pesquise e mantenha atualizados os dados dos clientes do escritório.</p></div><button className="primary-button" onClick={startNew}>+ Novo cliente</button></section>
 <div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, CPF/CNPJ, telefone ou cidade..."/><span className="muted">{filtered.length} de {clients.length}</span></div>
 {open&&<form className="panel data-form" onSubmit={save}><div className="panel-heading"><div><span className="eyebrow">{editing?"EDIÇÃO":"NOVO CADASTRO"}</span><h3>{editing?"Editar cliente":"Cadastrar cliente"}</h3></div></div><div className="form-grid"><label>Nome completo<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome do cliente"/></label><label>CPF/CNPJ<input value={form.document} onChange={e=>setForm({...form,document:e.target.value})} placeholder="CPF ou CNPJ"/></label><label>RG<input value={form.rg} onChange={e=>setForm({...form,rg:e.target.value})} placeholder="RG"/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="cliente@email.com"/></label><label>Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="(31) 99999-9999"/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})} placeholder="(31) 99999-9999"/></label><label>Endereço<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Rua, número, complemento"/></label><label>Cidade<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Cidade"/></label><label>UF<input maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})} placeholder="MG"/></label></div><label className="full-field">Observações<textarea className="settings-textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Observações internas do cliente"/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>{setOpen(false);setEditing(null)}}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?(editing?"Salvando...":"Cadastrando..."):(editing?"Salvar alterações":"Cadastrar cliente")}</button></div></form>}
 {!open&&error&&<p className="form-error">{error}</p>}{vehicleOpen&&selectedClient&&<form className="panel data-form" onSubmit={async e=>{e.preventDefault();setError("");const tenant=await tenantId();if(!tenant||!supabase)return;const{error}=await supabase.from("vehicles").insert({tenant_id:tenant,client_id:selectedClient,plate:vehicleForm.plate.toUpperCase()||null,renavam:vehicleForm.renavam||null,brand:vehicleForm.brand||null,model:vehicleForm.model||null,year_model:vehicleForm.year_model?Number(vehicleForm.year_model):null});if(error){setError(error.message);return}setVehicleOpen(false);setSelectedClient(null);setVehicleForm({plate:"",renavam:"",brand:"",model:"",year_model:""});void load()}}><div className="panel-heading"><div><span className="eyebrow">NOVO VEÍCULO</span><h3>Vincular ao cliente</h3></div></div><div className="form-grid"><label>Placa<input value={vehicleForm.plate} onChange={e=>setVehicleForm({...vehicleForm,plate:e.target.value.toUpperCase()})} placeholder="ABC1D23"/></label><label>RENAVAM<input value={vehicleForm.renavam} onChange={e=>setVehicleForm({...vehicleForm,renavam:e.target.value})}/></label><label>Marca<input value={vehicleForm.brand} onChange={e=>setVehicleForm({...vehicleForm,brand:e.target.value})}/></label><label>Modelo<input value={vehicleForm.model} onChange={e=>setVehicleForm({...vehicleForm,model:e.target.value})}/></label><label>Ano modelo<input type="number" value={vehicleForm.year_model} onChange={e=>setVehicleForm({...vehicleForm,year_model:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setVehicleOpen(false)}>Cancelar</button><button className="primary-button">Vincular veículo</button></div></form>}
 <div className="panel"><div className="panel-heading"><div><span className="eyebrow">REGISTROS</span><h3>Clientes cadastrados</h3></div><span className="muted">{clients.length} registro(s)</span></div>{filtered.length===0?<div className="empty-inline">{clients.length===0?"Nenhum cliente cadastrado ainda.":"Nenhum cliente encontrado para essa busca."}</div>:<div className="data-list">{filtered.map(c=><div className="client-card" key={c.id}><div className="data-row"><div><strong>{c.name}</strong><small>{c.document||"Sem CPF/CNPJ"} • {c.phone||"Sem telefone"} {c.city?"• "+c.city:""}</small></div><div className="row-actions"><span>{c.whatsapp||c.email||""}</span><button className="secondary-button compact" onClick={()=>startEdit(c)}>Editar</button></div></div><div className="client-vehicle-section"><div className="panel-heading"><div><span className="eyebrow">GARAGEM DO CLIENTE</span><h3>Veículos vinculados</h3></div><button className="secondary-button compact" onClick={()=>{setSelectedClient(c.id);setVehicleForm({plate:"",renavam:"",brand:"",model:"",year_model:""});setVehicleOpen(true)}}>+ Veículo</button></div><div className="client-vehicle-list">{clientVehicles[c.id]?.length?clientVehicles[c.id].map(v=><div className="client-vehicle-row" key={v.id}><strong>{v.plate||"Sem placa"}</strong><span>{[v.brand,v.model].filter(Boolean).join(" ")||"Veículo"} {v.year_model?"• "+v.year_model:""}</span></div>):<span className="muted">Nenhum veículo vinculado.</span>}</div></div></div>)}</div>}</div></div>
}